var hierarchy =
[
    [ "com.seguros.controller.AdminController", "classcom_1_1seguros_1_1controller_1_1AdminController.html", null ],
    [ "com.seguros.performance.controller.AdminControllerPerfTest", "classcom_1_1seguros_1_1performance_1_1controller_1_1AdminControllerPerfTest.html", null ],
    [ "com.seguros.controller.AdminControllerTest", "classcom_1_1seguros_1_1controller_1_1AdminControllerTest.html", null ],
    [ "com.seguros.model.Administrador", "classcom_1_1seguros_1_1model_1_1Administrador.html", null ],
    [ "com.seguros.model.AdministradorTest", "classcom_1_1seguros_1_1model_1_1AdministradorTest.html", null ],
    [ "com.seguros.Service.AdminService", "classcom_1_1seguros_1_1Service_1_1AdminService.html", null ],
    [ "com.seguros.Service.AdminServiceTest", "classcom_1_1seguros_1_1Service_1_1AdminServiceTest.html", null ],
    [ "com.seguros.client.AdminVentana", "classcom_1_1seguros_1_1client_1_1AdminVentana.html", null ],
    [ "com.seguros.model.Cliente", "classcom_1_1seguros_1_1model_1_1Cliente.html", null ],
    [ "com.seguros.controller.ClienteController", "classcom_1_1seguros_1_1controller_1_1ClienteController.html", null ],
    [ "com.seguros.Service.ClientesPorSeguro", "classcom_1_1seguros_1_1Service_1_1ClientesPorSeguro.html", null ],
    [ "com.seguros.Service.ClientesPorSeguroTest", "classcom_1_1seguros_1_1Service_1_1ClientesPorSeguroTest.html", null ],
    [ "com.seguros.model.Contrato", "classcom_1_1seguros_1_1model_1_1Contrato.html", null ],
    [ "com.seguros.model.ContratoTest", "classcom_1_1seguros_1_1model_1_1ContratoTest.html", null ],
    [ "com.seguros.model.Duda", "classcom_1_1seguros_1_1model_1_1Duda.html", null ],
    [ "com.seguros.model.DudaTest", "classcom_1_1seguros_1_1model_1_1DudaTest.html", null ],
    [ "com.seguros.model.Factura", "classcom_1_1seguros_1_1model_1_1Factura.html", null ],
    [ "com.seguros.controller.FacturaController", "classcom_1_1seguros_1_1controller_1_1FacturaController.html", null ],
    [ "com.seguros.client.FacturaControllerClient", "classcom_1_1seguros_1_1client_1_1FacturaControllerClient.html", null ],
    [ "com.seguros.controller.FacturaControllerTest", "classcom_1_1seguros_1_1controller_1_1FacturaControllerTest.html", null ],
    [ "com.seguros.Service.FacturaService", "classcom_1_1seguros_1_1Service_1_1FacturaService.html", null ],
    [ "com.seguros.Service.FacturaServiceTest", "classcom_1_1seguros_1_1Service_1_1FacturaServiceTest.html", null ],
    [ "com.seguros.model.FacturaTest", "classcom_1_1seguros_1_1model_1_1FacturaTest.html", null ],
    [ "com.seguros.client.FacturaVenatana", "classcom_1_1seguros_1_1client_1_1FacturaVenatana.html", null ],
    [ "com.seguros.client.InicioSesionVentana", "classcom_1_1seguros_1_1client_1_1InicioSesionVentana.html", null ],
    [ "JFrame", null, [
      [ "com.seguros.client.DudasVentana", "classcom_1_1seguros_1_1client_1_1DudasVentana.html", null ],
      [ "com.seguros.client.PerfilVentana", "classcom_1_1seguros_1_1client_1_1PerfilVentana.html", null ]
    ] ],
    [ "JPanel", null, [
      [ "com.seguros.client.ui.SeguroListCellRenderer", "classcom_1_1seguros_1_1client_1_1ui_1_1SeguroListCellRenderer.html", null ]
    ] ],
    [ "JpaRepository", null, [
      [ "com.seguros.repository.AdministradorRepository", "interfacecom_1_1seguros_1_1repository_1_1AdministradorRepository.html", null ],
      [ "com.seguros.repository.ClienteRepository", "interfacecom_1_1seguros_1_1repository_1_1ClienteRepository.html", null ],
      [ "com.seguros.repository.ContratoRepository", "interfacecom_1_1seguros_1_1repository_1_1ContratoRepository.html", null ],
      [ "com.seguros.repository.DudaRepository", "interfacecom_1_1seguros_1_1repository_1_1DudaRepository.html", null ],
      [ "com.seguros.repository.FacturaRepository", "interfacecom_1_1seguros_1_1repository_1_1FacturaRepository.html", null ],
      [ "com.seguros.repository.SeguroCasaRepository", "interfacecom_1_1seguros_1_1repository_1_1SeguroCasaRepository.html", null ],
      [ "com.seguros.repository.SeguroCocheRepository", "interfacecom_1_1seguros_1_1repository_1_1SeguroCocheRepository.html", null ],
      [ "com.seguros.repository.SeguroRepository", "interfacecom_1_1seguros_1_1repository_1_1SeguroRepository.html", null ],
      [ "com.seguros.repository.SeguroVidaRepository", "interfacecom_1_1seguros_1_1repository_1_1SeguroVidaRepository.html", null ]
    ] ],
    [ "ListCellRenderer", null, [
      [ "com.seguros.client.ui.SeguroListCellRenderer", "classcom_1_1seguros_1_1client_1_1ui_1_1SeguroListCellRenderer.html", null ]
    ] ],
    [ "com.seguros.client.RegistroVentana", "classcom_1_1seguros_1_1client_1_1RegistroVentana.html", null ],
    [ "com.seguros.model.Seguro", "classcom_1_1seguros_1_1model_1_1Seguro.html", null ],
    [ "com.seguros.model.SeguroCasa", "classcom_1_1seguros_1_1model_1_1SeguroCasa.html", null ],
    [ "com.seguros.model.SeguroCasaTest", "classcom_1_1seguros_1_1model_1_1SeguroCasaTest.html", null ],
    [ "com.seguros.client.SeguroCasaVentana", "classcom_1_1seguros_1_1client_1_1SeguroCasaVentana.html", null ],
    [ "com.seguros.model.SeguroCoche", "classcom_1_1seguros_1_1model_1_1SeguroCoche.html", null ],
    [ "com.seguros.model.SeguroCocheTest", "classcom_1_1seguros_1_1model_1_1SeguroCocheTest.html", null ],
    [ "com.seguros.client.SeguroCocheVentana", "classcom_1_1seguros_1_1client_1_1SeguroCocheVentana.html", null ],
    [ "com.seguros.controller.SeguroController", "classcom_1_1seguros_1_1controller_1_1SeguroController.html", null ],
    [ "com.seguros.client.SeguroControllerAdmin", "classcom_1_1seguros_1_1client_1_1SeguroControllerAdmin.html", null ],
    [ "com.seguros.client.SeguroControllerClient", "classcom_1_1seguros_1_1client_1_1SeguroControllerClient.html", null ],
    [ "com.seguros.performance.controller.SeguroControllerPerfTest", "classcom_1_1seguros_1_1performance_1_1controller_1_1SeguroControllerPerfTest.html", null ],
    [ "com.seguros.client.SeguroManager", "classcom_1_1seguros_1_1client_1_1SeguroManager.html", null ],
    [ "com.seguros.SegurosApplication", "classcom_1_1seguros_1_1SegurosApplication.html", null ],
    [ "com.seguros.Service.SeguroService", "classcom_1_1seguros_1_1Service_1_1SeguroService.html", null ],
    [ "com.seguros.performance.service.SeguroServicePerfTest", "classcom_1_1seguros_1_1performance_1_1service_1_1SeguroServicePerfTest.html", null ],
    [ "com.seguros.Service.SeguroServiceTest", "classcom_1_1seguros_1_1Service_1_1SeguroServiceTest.html", null ],
    [ "com.seguros.client.SeguroVentana", "classcom_1_1seguros_1_1client_1_1SeguroVentana.html", null ],
    [ "com.seguros.model.SeguroVida", "classcom_1_1seguros_1_1model_1_1SeguroVida.html", null ],
    [ "com.seguros.model.SeguroVidaTest", "classcom_1_1seguros_1_1model_1_1SeguroVidaTest.html", null ],
    [ "com.seguros.client.SeguroVidaVentana", "classcom_1_1seguros_1_1client_1_1SeguroVidaVentana.html", null ],
    [ "com.seguros.model.TipoSeguro", "enumcom_1_1seguros_1_1model_1_1TipoSeguro.html", null ],
    [ "com.seguros.model.TipoSeguroTest", "classcom_1_1seguros_1_1model_1_1TipoSeguroTest.html", null ],
    [ "com.seguros.Service.UsuarioService", "classcom_1_1seguros_1_1Service_1_1UsuarioService.html", null ]
];